services:
  web:
    build: .
    environment:
      DEBUG: "0"
      SECRET_KEY: replace_me_with_long_random_secret
      ALLOWED_HOSTS: 94.183.191.3,127.0.0.1,localhost
      CSRF_TRUSTED_ORIGINS: http://94.183.191.3
      DB_ENGINE: sqlite
      SQLITE_NAME: /app_db/db.sqlite3   # вынесем файл БД в отдельный том
      STATIC_ROOT: /app_static
      MEDIA_ROOT: /app_media
    volumes:
      - app_db:/app_db
      - app_static:/app_static
      - app_media:/app_media
    restart: unless-stopped

  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - app_static:/var/www/static:ro
      - app_media:/var/www/media:ro
    restart: unless-stopped

volumes:
  app_db:
  app_static:
  app_media:
