# Generated by Django 5.2.7 on 2025-10-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ['client__name', 'entity__key'], 'verbose_name': 'Значение (устар.)', 'verbose_name_plural': 'Значения (устар.)'},
        ),
        migrations.AddField(
            model_name='client',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Атрибуты'),
        ),
    ]
